### ISSUE TITLE
[error]An error occurred while creating the pipeline.

### ISSUE THREAD

**Issue by tomkor** [jessehouwing/vsts-tfvc-tasks#14]
I want to check in AssemblyInfo.cs files after changed build version number with VersionUpdate.ps1 powershell script. 

[My build task ](http://www.tomaszkorczynski.eu/publikacja/CheckInPipelineError.jpg) and [log files](http://www.tomaszkorczynski.eu/publikacja/logs_384.zip)

**Comment by jessehouwing** [comment]
* Can you run a build with System.Debug = true?
* Are you running this against TFS or VSTS? 
* Is Visual Studio 2015 installed on your build server? 
 * If so RTM or Update 1?
* What's the powershell version you have installed? I've tested this against a Windows 10 machine (which runs Powershell 5) and the Hosted agent (which runs Powershell 4)
* What is the build agent version you're running?

**Comment by tomkor** [comment]
Hi
I have powershell version like this:

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  63

I use VSTS with visual studio 2015 update 1

Agent version is 1.94.0 was installed on my computer. This is not a hosted agent.

with system.debug=true i have  [build log like this](http://www.tomaszkorczynski.eu/publikacja/logs_385.zip)

**Comment by tomkor** [comment]
Into GAC)MSIL i have this assembly but version is 12.0. Into Visual studio 2015 folder version is 14.0. Probably this is a problem.

**Comment by jessehouwing** [comment]
are you running a 32 bit version of Windows or a 64 bit version?

**Comment by jessehouwing** [comment]
The Gac version should not be the issue. But I was hoping to get a little more information from my logging routines about where the assemblies were loaded from. It's one of the pain points of the current build agent. It ships with an incomplete Client Object Model, so I need to find these assemblies elsewhere.

**Comment by jessehouwing** [comment]
I have a test build I could share with your account... What's the VSTS account you're using?

**Comment by tomkor** [comment]
tomkor.visualstudio.com with user address devtomb@devtomb.pl

**Comment by tomkor** [comment]
Everything is ok now :)

**Comment by jessehouwing** [comment]
Thanks for letting me know.
