### ISSUE TITLE
Error Adding files to source control

### ISSUE THREAD

**Issue by JPGRodrigues** [jessehouwing/vsts-tfvc-tasks#22]
******************************************************************************

Starting task: Adding files to source control

******************************************************************************
Executing the powershell script: ****\tasks\TFVCAdd\1.1.69\TfvcAdd.ps1

The specified module '****\tasks\TFVCAdd\1.1.69/vsts-tfvc-shared.psm1' was not loaded because no valid module file was found in any module directory.
Adding ItemSpec: ****\s\dev\Deployment\drops\biz\MH_BIZ_ProductsCatalog, Recursive: Full, Apply Ignorefile: false

The term 'Invoke-DisposeSourceProvider' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The term 'Get-SourceProvider' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

******************************************************************************

Finishing task: TFVCAdd

******************************************************************************

Task TFVCAdd failed. This caused the job to fail. Look at the logs for the task for more details.
Worker Worker-ea855c1a-4f22-41c9-9e74-0d7278ac0722 finished running job ea855c1a-4f22-41c9-9e74-0d7278ac0722

******************************************************************************

**Comment by JPGRodrigues** [comment]
I manually copied script vsts-tfvc-shared.psm1 to the local (build agent) task folder, and the error was corrected. Deployment process has to be revisited.

**Comment by jessehouwing** [comment]
This is strange... The task itself has the specified file in the vsix and when I execute the build on a clean accoutn the agent installs it and the file shows up. It would be interesting to share the logs from the `agent\diag` folder, I may need to raise this with the product team.

There's not much I can do to influence the actual deployment steps other than build the vsix.

![image](https://cloud.githubusercontent.com/assets/4173387/13402784/27698dfe-df12-11e5-89f2-460b06405d20.png)

**Comment by JPGRodrigues** [comment]
My issue my be related to the fact I didn't install the extensions via marketplace. I used tfx build tasks upload!

**Comment by jessehouwing** [comment]
That would be it. 

You need to copy some files around in the build, you should be able to use:

```
./publish -force -release -publishlocal -serviceurl http://youraccount.visualstudio.com/DefaultCollection
```
