### ISSUE TITLE
Error cheking-in files

### ISSUE THREAD

**Issue by JPGRodrigues** [jessehouwing/vsts-tfvc-tasks#23]
******************************************************************************

Starting task: Check changes into source control

******************************************************************************
Executing the powershell script: ***\tasks\TFVCCheckin\1.1.69\TfvcCheckin.ps1
****\s\dev\Deployment\drops\biz\MH_BIZ_ProductsCatalog
No Add detected.
No Delete detected.

Unable to parse checkin note

Exception calling ".ctor" with "1" argument(s): "Value cannot be null.

Parameter name: values"

******************************************************************************

Finishing task: TFVCCheckin

******************************************************************************

**Comment by jessehouwing** [comment]
Looks like you've specified an empty note...

Can you share the contents of the Notes Field?

If you want to set no value, just don't specify that nite value at all.

I'll see about improving the error message.

**Comment by jessehouwing** [comment]
Released a new version with better Notes parsing.

I've replaces the old syntax with Json for more control over the actual Notes values.
