### ISSUE TITLE
Miltiple build with check-in trigger

### ISSUE THREAD

**Issue by tomkor** [jessehouwing/vsts-tfvc-tasks#24]
Hi again

Now I have problem with multiple build caused by check-in trigger (example with screenshot of m buld agent) 
![microsoft_visual_studio_team_services_-_2016-03-06_17 33 23](https://cloud.githubusercontent.com/assets/8578822/13555474/a9f5851c-e3c1-11e5-9211-84a00426ce7e.png)

My build definition is like this:

![microsoft_visual_studio_team_services_-_2016-03-06_17 35 19](https://cloud.githubusercontent.com/assets/8578822/13555487/ea9c3e94-e3c1-11e5-8261-a2b8e635ddb0.png)

with trigger like this:

![microsoft_visual_studio_team_services_-_2016-03-06_17 36 37](https://cloud.githubusercontent.com/assets/8578822/13555488/07e08fbe-e3c2-11e5-8e43-572327af6ab8.png)

Build number 16066_01 is my first build today. Other builds 160066_.. is automaticaly created for check-in like this: 

![microsoft_visual_studio_team_services_-_2016-03-06_17 39 48](https://cloud.githubusercontent.com/assets/8578822/13555513/761f3f20-e3c2-11e5-8f4f-2e40b76feccb.png)

**Comment by tomkor** [comment]
Last build 160066_13 have error like this: 

![microsoft_visual_studio_team_services_-_2016-03-06_17 42 15](https://cloud.githubusercontent.com/assets/8578822/13555533/cb742f6c-e3c2-11e5-875c-2d9aa13671fc.png)

**Comment by jessehouwing** [comment]
What exactly is the problem you're seeing? The final screenshot shows a connection issue between the agent and VSTS, but it's in the Get Sources step, so it doesn't seem to be related to my task.

If you're trying to prevent the build from diving into a build loop, be sure to check the 

> * [x] **Policy Override** \ **Bypass CI on check in**

option. Without it every checkin will fire off a new build. Alternatively update your CI trigger to ignore changes to the `AssemblyInfo.cs`. to do so click *add new Filter* and add 

> * [x] **Continuous Integration**
> * [x] Batch Changes
> * Include `$/Kancelaria`
> * Exclude `$/Kancelaria/eKancelaria/eKancelaria/properties/assemblyinfo.cs`

**Comment by jessehouwing** [comment]
It looks like you have the Bypass CI on checkin enabled if I look at the build logs, so the second option would be a temporary workaround. I'll check with Microsoft why the **NO_CI** comment isn't working.

**Comment by jessehouwing** [comment]
It looks like the NO_CI comment I'm adding is missing an extra `*`, i'll push a build which adds the correct number.

**Comment by jessehouwing** [comment]
Pushing a new build to the gallery in a couple of minutes

https://github.com/jessehouwing/vsts-tfvc-tasks/commit/f132cbe69937b5749100e0b0015d5ca90b65d5eb

**Comment by jessehouwing** [comment]
Build 1.1.712 should contain the fix.

**Comment by tomkor** [comment]
Now everything is ok. New, only one build 160066.14

Thanks for quick reaction

Best Regards
Tomasz Korczyński
