### ISSUE TITLE
Skip checkin on any shelveset

### ISSUE THREAD

**Issue by tbergstedt** [jessehouwing/vsts-tfvc-tasks#32]
I'd like to broaden or extend the "Skip checkin on Gated changes" feature to apply to whenever a shelveset is sent to the build. I don't think such builds are "gated" as build vNext sees it, at least we've had the issue that the changes were checked in even though this was not the intention.

**Comment by jessehouwing** [comment]
You're right that the builds are not treated as Gated. 

It would be relatively easy to detect whether this is a Shelveset build (the code is already there), but I know a few people are building to support "buddy builds" which only check in if the build succeeds. I don't know when I'll have time to fix this, I'm open to a pull request on this. The checks are already here: https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/vsts-tfvc-checkin/TfvcCheckin.ps1#L184 So it would require a quick update in the UI: https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/vsts-tfvc-checkin/task.json#L154 with a default value of False for backwards compatibility.

I don't think this is different than it was in XAML builds when doing buddy builds.

**Comment by jessehouwing** [comment]
Adding this to the Gated Checkin task.
What would you expect the behavior of the Update Shelveset task? Should it have a Skip gated, Skip shelveset and Error options?

**Comment by jessehouwing** [comment]
https://github.com/jessehouwing/vsts-tfvc-tasks/tree/Features/SkipShelveset

**Comment by jessehouwing** [comment]
If you can share your VSTS account name I can share you the latest preview version which should work for you.

**Comment by tbergstedt** [comment]
Hi,
Great, thanks for such fast response and fix. We use it in TFS On Premises,
could you possibly make it available for that as well?

Cheers,
Torbjörn

fre 3 juni 2016 kl 10:53 skrev Jesse Houwing <notifications@github.com>:

**Comment by jessehouwing** [comment]
Grab it from here: https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-tfvc-tasks

**Comment by jessehouwing** [comment]
A review of the tasks with a short description of how you're using it would be very appreciated.
