### ISSUE TITLE
File not found: 'TfvcAdd.js'

### ISSUE THREAD

**Issue by svsch0488** [jessehouwing/vsts-tfvc-tasks#51]
I'm getting the following error when using the "Add Files" Function on VSTS.

File not found: 'd:\a\_tasks\TFVCAdd_2ef90ef1-5298-4f6a-8b99-12933fed4de4\1.2.3\TfvcAdd.js'

Best regards,

Sven

**Comment by jessehouwing** [comment]
Somehow 3 commits that shouldn't have reached master did. I scrubbed them. New release has just gone live.
