### ISSUE TITLE
Unable to find task after install

### ISSUE THREAD

**Issue by gitddavis01** [jessehouwing/vsts-tfvc-tasks#53]
Hi! I'm having trouble finding the task to implement in my VSTS build after installing from the marketplace. I've tried looking under Build & the All sections, but have not been successful. I have tried installing it again thinking it didn't go through the 1st time, but get an error message saying a task with the same name already exists. Can you please tell me what I'm doing wrong? I'm looking forward to integrating this into our builds. Thanks!

**Comment by jessehouwing** [comment]
Sounds like what you're doing is right. Nothing I can really do about it.
Gave you contacted VSTS or marketplace support?
