### ISSUE TITLE
check in changes not working

### ISSUE THREAD

**Issue by jkwinder** [jessehouwing/vsts-tfvc-tasks#54]
We've had good success with this task in one vsts instance, but after moving the build definition and repo to a different vsts instance, we cannot get this task to work there.  One issue that occurs is that the Build_Repository_Name environment variable has no value and that causes an error on Get-ServiceEndpoint as near as we can tell.  There really are no differences in the build agent between the two environments (they are running on the same VM) nor are there any differences in the build definition.  We've looked into differences with the collection permissions for the service account which runs the build agent and can't see anything that would be causing this problem  Does anyone have any idea why that variable wouldn't be set?  We've also tried explicitly setting that variable, but then encounter another error shortly afterwards.

**Comment by jessehouwing** [comment]
I'm checking with the VSTS team, they're asking whether this is VSTS or TFS, what agent version, how the builds are triggered. If you can provide a log in debug mode where. This triggers would be appreciated.

**Comment by jkwinder** [comment]
This is VSTS.  Agent version is 2.122.  I can see about getting a log for you.

-Jeff

**Comment by jessehouwing** [comment]
Fixed with #78
