### ISSUE TITLE
Checkout Files regex not working

### ISSUE THREAD

**Issue by ankitdholakiya** [jessehouwing/vsts-tfvc-tasks#59]
When I use checkout regex

$(agent.builddirectory)\s\**\*ModuleMetaData.xml

The path is not found. I think regex is not supported in TFVC

**Comment by jessehouwing** [comment]
You need to pass in an itemspec. The format and options for itemspec in tfs
are well defined.

**Comment by ankitdholakiya** [comment]
Can you please give me link or example? I am not able to find it.

**Comment by jessehouwing** [comment]
https://docs.microsoft.com/en-us/vsts/tfvc/use-team-foundation-version-control-commands#specify-the-items-affected-by-a-command
