### ISSUE TITLE
TF14045: The identity Microsoft.TeamFoundation.System is not a recognized identity

### ISSUE THREAD

**Issue by rfrcarvalho** [jessehouwing/vsts-tfvc-tasks#62]
Currently we have a problem where everything works when a user schedules a build but the Nightly builds fail with: 
"##[error]System.Management.Automation.MethodInvocationException: Exception calling "CheckIn" with "1" argument(s): "TF14045: The identity Microsoft.TeamFoundation.System is not a recognized identity." ---> Microsoft.TeamFoundation.VersionControl.Client.IdentityNotFoundException: TF14045: The identity Microsoft.TeamFoundation.System is not a recognized identity. ---> System.Web.Services.Protocols.SoapException: TF14045: The identity Microsoft.TeamFoundation.System is not a recognized identity."

The GetSources step works fine, so the user must have permissions to get the source code, but somehow when Checking In the code changes, this happens.

Am I doing something wrong?

**Comment by jessehouwing** [comment]
This is why we have exposed the author field. I still haven't been able to
diagnose the issue behind this problem, but by overriding the author field
or leaving it empty will solve the issue.

This may cause the author to be the system identity and not the user
triggering the build, but I suspect this is what you want anyway.

**Comment by rfrcarvalho** [comment]
Thanks. Setting it to None solved the problem.
