### ISSUE TITLE
Running similar commands without deploying a task

### ISSUE THREAD

**Issue by mattp65** [jessehouwing/vsts-tfvc-tasks#65]
I'm looking to use a modifed version of these tasks in a build, but want to avoid the overhead of deploying and maintining a seperate "task" in the marketplace. There doesn't seem to be an easy path to porting these calls to a non-Task model though and I can't seem to find anything to realy documents running these from within a build.

I have tried putting the code into .PS1 files deployed inside a scripts folder and they run into all sorts of problems in loading the included modules and then connecting to the provider. I finally got the modules to load, but $distributedTaskContext isn't being set, so the connection won't work properly.

Do you have any guidance here? I can do this as a task, but long term, that is a lot more maintenance and requires more steps for someone to modify if needed. It seems like the functions being invovked have been replaced by something newer, but I can't find any reference to the replacements.

**Comment by jessehouwing** [comment]
I'd suggest calling tf.exe, that's way easier.
