### ISSUE TITLE
Error checking in

### ISSUE THREAD

**Issue by abvogel** [jessehouwing/vsts-tfvc-tasks#66]
2018-07-21T00:39:58.5008121Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "CheckIn" with "1" argument(s): "TF10141: No files checked in: resolve the conflicts and try again." ---> Microsoft.TeamFoundation.VersionControl.Client.CheckinException: TF10141: No files checked in: resolve the conflicts and try again.

Receiving an error after adding a few files, and then trying to Check-In with Auto Detect Adds enabled. If there are no files in the folder initially it works fine, but if it's adding to existing files it fails with the above error.

**Comment by abvogel** [comment]
Thanks!

**Comment by abvogel** [comment]
It seems odd, as I'm running this against a test folder that only I control-
1) Map folder and download from source control
2) Delete everything in folder
3) Copy zip file into folder
4) Extract zip file into folder, overwriting a few files and adding a few new files
5) Run the TFVC check-in with auto delete/add enabled

And that's when the error hits. Am I missing something obvious?

**Comment by jessehouwing** [comment]
Any pending changes on that folder in source control? The server is
blocking the checkin, it sees conflicting changes.

**Comment by abvogel** [comment]
Nope. I can get it to work if I delete all content in the folder and check it in via Visual Studio, and then run it for the first time. The second time I run it, it hits that conflict.

**Comment by jessehouwing** [comment]
Hmmm that's weird. What does `tf status` say followed by `tf checkin`?

**Comment by abvogel** [comment]
Hm...

Checking in add: Filename.xml
C:\vstsagent\a4\externals\vstsom\TF.exe : Conflict: The item $/Collection/Other/AnotherFile.xml already exists.
At line:1 char:1
+ C:\vstsagent\a4\externals\vstsom\TF.exe checkin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Conflict: The i...already exists.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Conflict: The item $/Collection/Other/Filename.xml already exists.
TF10141: No files checked in: resolve the conflicts and try again.

**Comment by jessehouwing** [comment]
It's detected as an add, not as an edit.

**Comment by abvogel** [comment]
Thanks for the help - I'm not sure why it's doing that still, but it gives me a direction.

**Comment by abvogel** [comment]
I was able to fix it by performing my extracting in a separate directory, then copying into the mapped folder. Apparently extracting to the directory caused it to register an add instead of update.
