### ISSUE TITLE
Build.SourceTfvcShelveset seems to be depricated by Microsoft!?...

### ISSUE THREAD

**Issue by btremblaymtech** [jessehouwing/vsts-tfvc-tasks#69]
Hi,
This weekend, Microsoft seems to have depricated the variable Build.SourceTfvcShelveset!!
I guess this broke your addin which is very useful for us.
The variable Build.SourceBranchName has the same value and still working.
Is it possible for you to very / correct the probleme?

thanks

Benoit

**Comment by jessehouwing** [comment]
Argh. Since I also have users on tfs 2015 and 2017 I'll have to figure out
how to correct this whole maintaining backwards compat.

**Comment by jessehouwing** [comment]
Sure looks like a regression, the docs still mention the variable:


Build.SourceTfvcShelveset | Defined if your repository is Team Foundation Version Control. If you are running a gated build or a shelveset build, this is set to the name of the shelveset you are building. Note: This variable yields a value that is invalid for build use in a build number format.
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts

The code in the vsts-agent repo still seems to (try to ) populate it. Can you provide more information about the exact agent version and can you provide me a log of the build with the following two options enabled:


```
system.debug = true
agent.diagnostic = true
```

**Comment by btremblaymtech** [comment]
Hi,  Thanks for investigated! :-)

Here is my log file.  Hope this helps

Benoit
[logs_13038.zip](https://github.com/jessehouwing/vsts-tfvc-tasks/files/2368180/logs_13038.zip)
