### ISSUE TITLE
Service EndPoint Error using Check Out Task

### ISSUE THREAD

**Issue by leahymichael** [jessehouwing/vsts-tfvc-tasks#70]
We've been using the CheckOut / CheckIn tasks for a while now as part of our builds;  this morning the CheckOut task started throwing the following error:

**System.Collections.Generic.KeyNotFoundException: The service endpoint society was not found
PowerShell script completed with 1 errors.**

This is running against local (private) build agents.  I've made sure the build agent code, and the VS Install on the build agent is current, but neither helped the error.

**Comment by jessehouwing** [comment]
Thus has been fixed in the latest agent version. Please upgrade your agent
to 2.140

**Comment by leahymichael** [comment]
Ok thanks, I'm on 2.138.6 currently - I ran the Agent Auto-Update and didn't realize it actually failed, so looks like I'll have to manually re-deploy the agents (again - had to do that on last update as well).  I will try that and hopefully that does the trick.

**Comment by leahymichael** [comment]
Manually updating to 2.140 agent fixed the issue. Thanks for quick response.
