### ISSUE TITLE
Check-in changes broken following VSTS rebranding to Azure DevOps

### ISSUE THREAD

**Issue by roizentner** [jessehouwing/vsts-tfvc-tasks#71]
Hi,

Since Microsoft's announcement of the VSTS rebranding into Azure DevOps, the task is throwing the following exception:
```
##[error]System.Collections.Generic.KeyNotFoundException: The service endpoint Votiro was not found
    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

Please advise.

**Comment by jessehouwing** [comment]
Update your agent.

**Comment by roizentner** [comment]
I updated to the latest (v2.140.0) agent as you suggested and I can confirm it works...
Do you know what change made old agents stop supporting your task?

**Comment by jessehouwing** [comment]
The agent forgot to set the required variables for the legacy powershell hander to work

**Comment by roizentner** [comment]
Interesting. How could've that happened if I haven't updated my agent?

Thanks for the tip anyway!
