### ISSUE TITLE
Checkin task returns changesetId - needed to link to workitem

### ISSUE THREAD

**Issue by cordoyoa** [jessehouwing/vsts-tfvc-tasks#73]
I don't know if this is the correct way, but defining $changesetid as output variable, this Id can be approach in next steps... (for example, to link via API to a workitem).
Any other workaround for this?

Thank you for your help.

**Comment by jessehouwing** [comment]
Currently no workaround. Using a bit of powershell to query the workspace
version wouldn't be hard

These tasks are on the backlog for an overhaul, so I won't be doing major
rework to them.
