### ISSUE TITLE
[feature-request] Allow minimatch for files to check in

### ISSUE THREAD

**Issue by yrtimiD** [jessehouwing/vsts-tfvc-tasks#74]
I think this can be done by firstly getting list of pending changes and then applying minimatch pattern over it

**Comment by jessehouwing** [comment]
I've considered this, but it's confusing between the syntax TFVC expects and the task. Unless there is a radio button to choose between the options, it'll be hard to use. I don't think many people will understand the impact.

I had started working on a v2 based on a completely new approach, I could see it working there maybe...
