### ISSUE TITLE
Build Number in check-in comments

### ISSUE THREAD

**Issue by santoorman** [jessehouwing/vsts-tfvc-tasks#76]
I Would like to use the build number (which we change during the pipeline) in the check-in comments - but nothing seems to work - they all say ***NO_CI*** - using Link Settings - but it's always pre-pending Parameters at the front so not sure that tried Parameters.BuildNumber, Parameters.Build.BuildNumber, etc.

![image](https://user-images.githubusercontent.com/629163/51068790-d9ef4780-15d7-11e9-9d28-4a46769c3c5f.png)

how can I do this?

Also ideally I would be able to add other text in addition to the build number but not 100% necessary ("Checkin for build ... ")

thanks for making this!

**Comment by jessehouwing** [comment]
Use one of my other tasks, the set variable tasks from the variable toolkit to set the correct comment format. Then link the required input parameters to that.

**Comment by santoorman** [comment]
thanks for quick reply - tried that but not working - I guess I need to use a different parameter or specify it differently? thanks

![image](https://user-images.githubusercontent.com/629163/51090184-ef29ba80-172c-11e9-876c-cc35fe9ed9d3.png)

![image](https://user-images.githubusercontent.com/629163/51090182-e802ac80-172c-11e9-9ebf-7c0c0a6e97ec.png)

**Comment by jessehouwing** [comment]
That way you shouldn't need to link anything, it's taking all parameters
from context.

**Comment by santoorman** [comment]
OK thanks well why are my checkin comments  ***NO_CI***  -- something does not appear to be correct.... thanks..

**Comment by jessehouwing** [comment]
That comment is auto-appended by the task if the settings are to prevent new CI builds to trigger: 
https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/vsts-tfvc-checkin/TfvcCheckin.ps1#L214-L225

But it should be appended to **your** comment.

**Comment by jessehouwing** [comment]
Why are you using the "Link" option anyway and not just put the comment directly into the Checkin task?

**Comment by santoorman** [comment]
because I want to put the actual BuildNumber in the checkin comment... is there an easier way to do this?  thanks

**Comment by jessehouwing** [comment]
Just edit the checkin Comment textbox on the checkin task directly and use the standard variable syntax, just like you did in the set variable task. No need for any linking, those are for linking to variable sets and task groups.

**Comment by santoorman** [comment]
Oh Okay thanks, much appreciated.

**Comment by santoorman** [comment]
oh, ok thanks!
