### ISSUE TITLE
Optionally check-in changes based on build variable value

### ISSUE THREAD

**Issue by icnocop** [jessehouwing/vsts-tfvc-tasks#79]
Hi.

Thank you for TFS TFVC tasks.

I would like to request the ability to check-in changes based on a build variable.

For example, I would like to set a build variable at queue time to indicate whether or not to check-in changes.

If the build variable is set to true, then the "TFVC - Check-in changes" step will check-in changes.
If the build variable is set to false, then the "TFVC - Check-in changes" step will not check-in changes.

This is helpful when I want to optionally check-in a shelveset with a build.

I'm using TFS 2015 Update 4 where conditions can't be set on a build step.

Since this only affects users using an older version of TFS, I'm willing to re-use an existing variable like `ConfirmUnderstand` (if possible), but even if that variable is set to false, the TFVC task still checks-in changes according to https://github.com/jessehouwing/vsts-tfvc-tasks/issues/64.

Thank you.

**Comment by jessehouwing** [comment]
I'm very hesitant to add this given conditionals exist in tfs 2017 and up.

**Comment by icnocop** [comment]
I understand and thanks for your consideration.

I was able to use a PowerShell task to abort the build on a condition before the check in step.
